language: python
python:
    - "2.7"

branches:
    only:
        - master

install:
    - travis_retry pip install .
    - travis_retry pip install pyephem pyserial kivy
    - "[[ $TRAVIS_PYTHON_VERSION == '2.6' ]] && pip install unittest2 || true"
script:nosetests --with-coverage --cover-package=beets

before_script:
    - "[[ $TRAVIS_PYTHON_VERSION == '2.7' ]] && pip install coveralls || true"
after_success:
    - "[[ $TRAVIS_PYTHON_VERSION == '2.7' ]] && coveralls || true"
